test:
  assertStdoutEqual: Hi

  greetings:
    - Hi
    - Hello
   
  names:
    - value: Juan
      mutate: radamsa
      mutate_qty: 3
    - Maria

  execute:
    - [python, hello.py, $(greetings) $(names)]
