tests:
  assertStdoutEqual: ""
  host:
    - www.uflow.biz
  install:
    - [apt update]
    - [apt -y install testssl.sh]
    - [echo "testssl -oC output.csv '$1'" > test.sh]
    - [echo "grep 'LOW|MEDIUM|HIGH|CRITICAL' output.csv" >> test.sh]
    - [chmod 700 test.sh]
  execute:
    - [./test.sh $(host)]
