test:
  assertStdoutEqual: Hi

  greetings:
    - Hi
    - Hello
   
  names:
    - value: Juan
      mutate: true
      mutator: radamsa
      mut_qty: 3
    - Maria

  execute:
    - [python, hello.py, $(greetings) $(names)]
