test:
  assertStdoutEqual: Hi

  greetings:
    - Hi
    - Hello
   
  names:
    - Juan
    - Maria
   
  install:
    - [pip, install, -r, requirements.txt]

  execute:
    - [python, hello.py, "$(greetings) $(names)"]
